### ISSUE TITLE
Contribution or code of conduct for pull request

### ISSUE THREAD

**Issue by jonakls** [BryanGamingDV/chatlab-2023#6]
Add the nomenclature or agreements of how the code structure is to be informed at the time of making a pull request, this without conflicting with the developer.

Examples:

* [CONTRIBUTING.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md)
* [CODE_OF_CONDUCT.md](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

**Comment by BryanGmG** [comment]
Code conduct and pull request template created!
